# Generated by Django 2.1 on 2018-10-22 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181021_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seats',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
