# Generated by Django 2.1 on 2018-10-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181022_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
