# Generated by Django 2.1 on 2018-10-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181022_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats_left',
            field=models.IntegerField(verbose_name=models.IntegerField()),
        ),
    ]
